export enum ErrorCode {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  HTTP_EXCEPTION = 'HTTP_EXCEPTION',

  // identity
  INVALID_EMAIL = 'INVALID_EMAIL',

  // accounts
  TENURE_ALREADY_CLOSED = 'TENURE_ALREADY_CLOSED',
  TRANSFER_ALREADY_RESOLVED = 'TRANSFER_ALREADY_RESOLVED',

  // channels
  CONNECTION_ALREADY_DEACTIVATED = 'CONNECTION_ALREADY_DEACTIVATED',

  // entitlement
  SUBSCRIPTION_ALREADY_TERMINAL = 'SUBSCRIPTION_ALREADY_TERMINAL',

  // automation
  INVALID_EXECUTION_TRANSITION = 'INVALID_EXECUTION_TRANSITION',

  // flows
  FLOW_SESSION_ALREADY_CLOSED = 'FLOW_SESSION_ALREADY_CLOSED',

  // ingestion
  DUPLICATE_INBOUND_EVENT = 'DUPLICATE_INBOUND_EVENT',

  // moderation
  MODERATION_DECISION_ALREADY_RESOLVED = 'MODERATION_DECISION_ALREADY_RESOLVED',
}
